
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnsluzykhazoardgcfpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhuc2x1enlraGF6b2FyZGdjZnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MzI5OTUsImV4cCI6MjA4MTEwODk5NX0.qFDum5P7Cnnwi5Pgh82YBS9qOvXnqtvSdx-3QrusyaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
